config/routes.rb
# == Route Map
#
#          Prefix Verb URI Pattern                Controller#Action
#   recipes_index GET  /recipes/index(.:format)   recipes#index
#            root GET  /                          recipes#index
#
# for root it is possible to get search in F2F (c) with ?looking_for=
#
#   greeter_hello GET  /greeter/hello(.:format)   greeter#hello
# greeter_goodbye GET  /greeter/goodbye(.:format) greeter#goodbye
#         contact GET  /contact(.:format)         recipes#contact
#           about GET  /about(.:format)           recipes#about
#

Rails.application.routes.draw do
  get 'recipes/index'
  root 'recipes#index'
  resources :recipes do
    member do
      patch :update_span
    end
  end
  get 'greeter/hello'
  get 'greeter/goodbye'
  get 'contact' => 'recipes#contact', as: :contact
  get 'about' => 'recipes#about', as: :about
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe
  # Implement HTTParty for search results
  include HTTParty

  key_value = ENV['FOOD2FORK_KEY']
  host_port = ENV['FOOD2FORK_SERVER_AND_PORT'] || 'www.food2fork.com'
  base_uri "http://#{host_port}/api"
  default_params key: key_value
  format :json

  def self.for(keyword)
    get('/search', query: { q: keyword })['recipes'] # in food2fork.com/about/api 's response:  count: value recipes: value
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/greeter_controller.rb
# frozen_string_literal: true

class GreeterController < ApplicationController
  def hello
    random_names = %w[Alex Joe Michael]
    @name = random_names.sample
    @time = Time.zone.now
    @times_displayed ||= 0 # Should work only in gaps of one request
    @times_displayed += 1
  end

  def goodbye
    random_names = %w[Alex Joe Michael]
    @name = random_names.sample
  end
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  def index
    # @recipes = ['celery root']
    @search_term = params[:looking_for] || 'celery root' # @recipes
    # @search_term = @search_term.join(', ') if @search_term.is_a? Array
    # 'cause complete raving reason @recipe line was absent in #add method
    @recipes = Recipe.for(@search_term) || []
  end

  # def add
  #   @recipe = Recipe.find_by(f2f_id: params[:f_id])
  #   unless @recipe
  #     @recipe = Recipe.create(
  #       f2f_id: params[:f_id],
  #       rsite: params[:f2f_url],
  #       rpic: params[:image_url],
  #       title: params[:title]
  #     )
  #   end
  #   unless recipes
  #     recipes << @recipe
  #   end
  # end
  #
  # def remove
  #   @recipes&.destroy
  #   # @userrecipe = UserRecipe.find_by(recipe_id: params[:f_id], user_id: current_user.id)
  #   redirect_back(fallback_location: root_path)
  # end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/greeter_helper.rb
# frozen_string_literal: true

module GreeterHelper
  def formatted_time(time)
    # time string in AM/PM format
    time.strftime('%I:%M%p')
  end
end

app/helpers/recipes_helper.rb
# frozen_string_literal: true

module RecipesHelper
  def formatted_rank(rank)
    # time string in AM/PM format
    rank.round(2) if rank.present?
  end
end

app/views/greeter/goodbye.html.erb
<h1>Bye, <%= @name %></h1>

app/views/greeter/hello.html.erb
<h1>Greetings, <%= @name %></h1>
<p>The time now is <%= formatted_time(@time) %></p>
<p>This page has been viewed <%= @times_displayed %> times(s)</p>

<p><%= link_to "Google", "http://www.google.com" %></p>
<p><%= link_to "Goodbye", greeter_goodbye_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title><%= yield(:title) %></title><!--  RecipeFinderForFork2forkcom -->
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
      <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
      <%= csrf_meta_tags %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container" style="margin-top: 60px">
      <div class="row">
        <div class="col-md-3 well">
          <p class="text-uppercase"><strong>Some Favorites</strong></p>
          <span id="snan_ n1">
            <a class="badge badge-default" href="http://www.pairuptocode.com/exercises/bootstrap_before.html#">Celery Root</a></span>
          <span id = "span_n2">
            <a class="badge badge-default" href="http://www.pairuptocode.com/exercises/bootstrap_before.html#">Spaghetti Squash</a></span>
          <span id = "span_n3">
            <a class="badge badge-default" href="http://www.pairuptocode.com/exercises/bootstrap_before.html#">Killer Mushrooms</a></span>

            <div class="row">
              <div class="form-group col-md-8 col-md-offset-2">
              </div>
            </div>

          <%= form_tag('/', class: 'form-inline', method: 'get') do %>

            <div class="row">
              <div class="form-group col-md-8 col-md-offset-2">
                <%= text_field_tag :looking_for, @search_term, placeholder: "Enter veggie's name", id: 'input_sm_field', class: 'input input-sm', style: 'width: 100%' %>
              </div>
            </div>

            <div class="row">
              <div class="form-group col-md-8 col-md-offset-2">
              <!--<button class="btn btn-danger btn-sm" name="button" type="submit">Search recipes</button>-->
               <%= button_tag 'Search', type: 'submit', id: 'btn_sm_button', class: 'btn btn-danger btn-sm', data: {disable_with: "<i class='fa fa-circle-o-notch fa-spin'></i> Searching…"} %>
              </div>
            </div>

          <% end %>
        </div>
        <div class="col-md-9">
          <% content_for :examples do %>
          <div class="alert bg-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>Well!</strong> Have you had your daily dose of veggies today??
          </div>
          <% end %>
          <%= yield(:examples) if yield(:enabled_examples) == 'true' %>
          <blockquote>
            <p>Take care of your body. It's the only place you've to live
            </p>
            <small>Jim Rohn</small>
          </blockquote>
        </div>
        <%= render 'shared/examples' if yield(:enabled_examples) == 'true' %>
      </div>
    </div>
    <div class="container"><%= yield %></div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script>
      $(document).ready(function(){
        <% session[:button_clicks] ||= 3%>
        function count() {
          <% (session[:button_clicks] % 3).zero? ? session[:button_clicks] = 1 : session[:button_clicks] += 1 %>
          $("#span_n<%=session[:button_clicks].to_s%>").html("<a class='badge badge-default' href='<%= request.original_url%>'><%= @search_term %></a>");
        }

        $('#btn_sm_button').click(
          function() {
            count();
        });
      });
    </script>
  </body>
  <hr>
  <footer>
    <p class="text-center">Powered By Food2Fork.com</p>
  </footer>
</html>

app/views/recipes/about.html.erb
<% provide(:about, "active") %>
<% provide(:title, "About") %>
<% provide(:enabled_examples, 'false') %>
<div class="row" style="margin-top: 60px;">
        <div class="col-md-4"></div>
        <div class="col-md-4">
        <p>Author: Alex Zhevlakov &copy;</p></div>
</div>

app/views/recipes/contact.html.erb
<% provide(:contact, "active") %>
<% provide(:title, "Contact") %>
<% provide(:enabled_examples, 'false') %>
<div class="row" style="margin-top: 60px;" >
        <div class="col-md-4"></div>
        <div class="col-md-4">
        <a href="https://github.com/JuPlutonic"> <p>My Github</p> </a></div>
</div>

app/views/recipes/index.html.erb
<% provide(:home, 'active') %>
<% provide(:title, 'Home') %>
<% provide(:enabled_examples, 'true') %>
<h2>Searching for - <%= @search_term %></h2>
<% if @recipes.nil? or @recipes == [] %>
  <p><h2>No recipes found with <%= @search_term %></h2></p>
<% else %>
  <table border=".5">
    <tr>
      <th>Image</th>
      <th>Title</th>
      <th>Social rank</th>
    </tr>
    <% @recipes.each do |recipe| %>
      <tr class=<%= cycle('even', 'odd') %>>
        <td><%= link_to(image_tag(recipe['image_url'], size: '100x100'), recipe['source_url']) unless recipe['image_url'].blank? %></td>
        <td><%= link_to(sanitize(recipe['title']), recipe['source_url']) %></td>
        <td><span class="pull-right badge badge-important" style='margin-right: 16px'><%= formatted_rank(recipe['social_rank']) %></span></td>
      </tr>
    <% end %>
  </table>
<% end %>
<script>
  $('#input_sm_field').val("Enter veggie's name");
</script>

app/views/shared/_examples.html.erb
<ul class="thumbnails" style="list-style: none;">
  <li class="col-sm-6 col-md-3">
    <a href="#" class="thumbnail">
      <img src="http://lorempixel.com/150/100/food/7" />
    </a>
  </li>
  <li class="col-sm-6 col-md-3">
    <a href="#" class="thumbnail">
      <img src="http://lorempixel.com/150/100/food/5" />
    </a>
  </li>
  <li class="ccol-sm-6 col-md-3">
    <a href="#" class="thumbnail">
      <img src="http://lorempixel.com/150/100/food/6" />
    </a>
  </li>
</ul>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"><b>Vegetable recipes</b></a>

  </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= yield(:home) %>"><%= link_to "Home", root_path %></li>
        <li class="<%= yield(:about) %>"><%= link_to "About", about_path %></li>
        <li class="<%= yield(:contact) %>"><%= link_to "Contact", contact_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>